config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  
  resources :questions
  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: %i[index]
  resources :hashtag_lists, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  after_create :connect_hashtag_list

  belongs_to :question
  belongs_to :hashtag_list, optional: true

  def connect_hashtag_list
    hashtag = HashtagList.find_by(body: self.body.downcase)
    # Вернет true, если хештег уже существует
    if hashtag
      hashtag.hashtags << self
      self.hashtag_list = hashtag
    else
      HashtagList.create(body: self.body.downcase, hashtags: [self])
    end
  end
end

app/models/hashtag_list.rb
class HashtagList < ApplicationRecord
  has_many :hashtags, dependent: :destroy
  has_many :questions, through: :hashtags
end

app/models/question.rb
class Question < ApplicationRecord
  after_save :hashtag_parse

  belongs_to :user
  belongs_to :who_ask, class_name: "User", optional: true

  has_many :hashtags, dependent: :destroy
  has_many :hashtag_lists, through: :hashtags, dependent: :destroy

  private

  def hashtag_parse
    self.hashtags.destroy_all

    # Парсинг хештегов у вопроса
    HashtagParser.parse(self.body).each do |element| 
        self.hashtags << Hashtag.create(body: element[:text], question: self)
    end

    # Парсинг хештегов у ответа
    if answer
      HashtagParser.parse(self.answer).each do |element| 
          self.hashtags << Hashtag.create(body: element[:text], question: self)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  before_save :downcase_nickname

  validates :email, presence: true, uniqueness: true

  has_many :questions, dependent: :delete_all

  def to_param
    nickname
  end

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end

  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
  
end

app/controllers/hashtag_lists_controller.rb
class HashtagListsController < ApplicationController
  def show
    @hashtag = HashtagList.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[update destroy edit]

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    if current_user.present?
      question_params[:who_ask] = current_user
    end

    @question = Question.create(question_params)

    redirect_to user_path(@question.user), notice: 'Новый вопрос создан!'
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    @question.update(question_params)

    redirect_to user_path(@question.user), notice: 'Сохранили вопрос!'
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc)
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def edit
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user&.save
      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
      @questions = @user.questions.order(created_at: :desc)
      @question = Question.new(user: @user)
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/hashtag_lists_helper.rb
module HashtagListsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtag_lists/show.html.erb
<div class="container mt-sm">
  <h2 class="title-lg">Все вопросы и ответы с хештегом: #<%= @hashtag.body %></h2>
</div>

<% @hashtag.hashtags.uniq{ |hashtag| hashtag.body && hashtag.question }.each do |hashtag| %>
  <div class="mt-sm container">
    <%= render "questions/question", question: hashtag.question %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar">
        <p class="title-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to "@#{current_user.nickname}", user_path(current_user), class: 'mr-sm' %>
            <%= button_to 'Выйти', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Вход', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
      <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-ssm">
  <% if question.who_ask == question.user %>
    <p class="text-grey">Автор задал вопрос сам себе (<%= link_to "@#{question.who_ask.nickname}", user_path(question.who_ask) %>)</p>
  <% elsif question.who_ask.present? %>
    <p class="text-grey">Автор вопроса: <%= link_to "@#{question.who_ask.nickname}", user_path(question.who_ask) %></p>
  <% else %>
    <div class="text-grey">Автор вопроса аноним</div>
  <% end %>
</div>

<div class="mb-ssm">
  <% if question.hashtags %>
    <% question.hashtags.each do |hashtag| %>
      <% question.body.gsub!("##{hashtag.body}", link_to("##{hashtag.body}", hashtag_list_path(hashtag.hashtag_list))) %>
    <% end %>
  <% end %>

  <%= question.body.html_safe %>
</div>

<% unless question.who_ask == question.user %>
  <div class="mb-ssm">
    <p class="text-grey">Вопрос задан пользователю: <%= link_to "@#{question.user.nickname}", user_path(question.user) %></p>
  </div>
<% end %>

<% if question.answer.present? %>
  <div class="mb-sm mt-md text-dark-red">
    <% if question.hashtags %>
      <% question.hashtags.each do |hashtag| %>
        <% question.answer.gsub!("##{hashtag.body}", link_to("##{hashtag.body}", hashtag_list_path(hashtag.hashtag_list))) %>
      <% end %>
    <% end %>

    <%= question.answer.html_safe %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>

      <%= link_to fa_icon(edit_icon), edit_question_path(question),
        title: 'Изменить вопрос', class: 'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question),
        method: :delete, title: 'Удалить вопрос' %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>
  <p class="mb">для <%= link_to "@#{@user.nickname}", user_path(@user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>

  <%= render 'question', question: @question %>

  <p class="mt"><%= link_to "Все вопросы", questions_path %></p>
</div>

app/views/users/_no_questions.html.erb
<div class="container text-center">
  <p class="title-sm text-grey">
    У этого пользователя пока никто ничего не спросил
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  <%= link_to "Дай, спрошу!", new_question_path(user_id: user),
    class: 'button button-main' %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование пользователя</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
      class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.present? %>
  <div class="user-box">
    <h2 class="title-lg mt-lg"><%= @user.name %></h2>

    <% if current_user == @user %>
      <p class="mt mb-lg">
        <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
      </p>
    <% end %>

    <p class="text-bold mt mb-lg">@<%= @user.nickname %></p>
  </div>

  <div class="container">
    <%= link_to "Спроси меня", new_question_path(user_id: @user.id),
      class: 'button button-yellow' %>

    <p class="mt">
      <%= render 'questions/form', question: @question %>
    </p>
  </div>

  <% if @questions.any? %>
    <div class="container mt-sm">
      <h2 class="title-lg">
        <%= @questions.count %>
        <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
      </h2>
    </div>

    <% @questions.each do |question| %>
      <div class="mt-sm container">
        <%= render question %>
      </div>
    <% end %>
  <% else %>
    <%= render partial: 'no_questions', locals: {user: @user} %>
  <% end %>
<% else %>
  <div class="user-box">
    <h2 class="title-lg mt-lg">Пользователь не найден =(</h2>
  </div>
<% end %>